# Generated by Django 2.0.5 on 2018-11-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование:')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('slug', models.SlugField(unique=True, verbose_name='Адрес на сайте:')),
                ('image', models.ImageField(upload_to='main/static/images', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
        migrations.AlterIndexTogether(
            name='main',
            index_together={('id', 'slug')},
        ),
    ]
