# Generated by Django 2.0.5 on 2019-01-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_blog_imagesforblog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='imagesforblog',
            name='image',
            field=models.ImageField(upload_to='static/images/blogs/%m', verbose_name='Изображение'),
        ),
    ]
