# Generated by Django 2.0.5 on 2019-01-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20181221_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='/static/images/profile_default.png', upload_to='static/images/users/%Y', verbose_name='Аватарка'),
        ),
    ]
